version: '3.8'
services:
  sonata-auth-service:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: auth-microservice-image
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - test-env-variables.env
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
